### ISSUE TITLE
Compiling on Centos 7 for Centos 6 doesn't work

### ISSUE THREAD

**Issue by jdarnold** [wheybags/glibc_version_header#19]
I have the following test file:

```
#include <string>
#include <iostream>
#include <stdlib.h>

int main()
{
  std::string testing("Test");

  char* tm = (char*)malloc(100);

  std::cout << "This is a " << testing << "\n";

  return 0;
}
```

and the following Makefile:

```
CXXFLAGS=-include force_link_glibc_2.12.2.h

LDFLAGS=-static-libgcc -static-libstdc++

.SUFFIXES: .o .c .cxx. .cpp

SRCS =  testglib.cpp

OBJS = $(SRCS:.cpp=.o)

testglib : $(OBJS)
        $(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)
```

If I build testglib on Centos 7 and try to run it on Centos 6, I get:

`./testglib: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./testglib)`

If I do an 'nm testglib' on the centos 7 system, I see all of the symbols using @@GLIBC_2.2.5, except for memcpy:

```
00000000006d6220 b marker.8744
                 U mbrtowc@@GLIBC_2.2.5
                 U mbsnrtowcs@@GLIBC_2.2.5
                 U mbsrtowcs@@GLIBC_2.2.5
                 U memchr@@GLIBC_2.2.5
                 U memcmp@@GLIBC_2.2.5
                 U memcpy@@GLIBC_2.14
                 U memmove@@GLIBC_2.2.5
                 U memset@@GLIBC_2.2.5
                 U __newlocale@@GLIBC_2.2.5
```

Any idea why?

**Comment by wheybags** [comment]
The problem here is the use of c++. libstdc++ internally uses libc calls, and ofc it wasn't compiled using this project. You can get this to work by compiling libstdc++ with this project, but it is a bit more involved than c. I do have a project that I was working on to make this whole process pretty easy, but unfortunately I haven't found time to work on it in a  while.
So basically, for now, this project is c only, sorry :(
